<a href="https://colab.research.google.com/github/hetnanoz/data-science-bootcamp/blob/master/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from numpy import *
np.__version__

'1.18.4'

In [4]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [13]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [14]:
x.dtype

dtype('float64')

In [15]:
x.shape

(3,)

### 2D Array

In [16]:
x = np.array([[1,2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x = np.array([[1,2,4], [4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [20]:
x.shape

(2, 3)

### 3D Array

In [21]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     [[4,1,3],
      [4,2,1]],
     [[4,5,6],
     [3,4,7]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 5, 6],
        [3, 4, 7]]])

In [22]:
x.ndim

3

In [23]:
x.shape

(3, 2, 3)

### TYPY DANYCH

In [24]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [25]:
A = np.array([1.0,2.6,3.3])
A.dtype

dtype('float64')

In [26]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [27]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [28]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [29]:
A = np.array([1.0,2.6,3.3], dtype='int')
A.dtype

dtype('int64')

In [30]:
A

array([1, 2, 3])

In [31]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [32]:
A = np.array([24,120,230], dtype=np.int8)
A.dtype

dtype('int8')

In [33]:
A = np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')

### TWORZENIE TABLIC

In [34]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [42]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [43]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [44]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### PODSTAWOWE OPERACJE NA TABLICACH

In [47]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [48]:
A+B

array([6, 0, 7, 4])

In [49]:
A - B

array([0, 2, 1, 0])

In [50]:
A*B

array([ 9, -1, 12,  4])

In [51]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [52]:
np.add(A, B)

array([6, 0, 7, 4])

In [53]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [54]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [55]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [56]:
A + 3

array([6, 4, 7, 5])

In [57]:
2 * A

array([6, 2, 8, 4])

In [58]:
A + 3*B

array([12, -2, 13,  8])

## Mnożenie macierzowe

In [59]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [60]:
X * Y

array([[6, 0],
       [2, 0]])

In [61]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [62]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [63]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [64]:
X @ Y

array([[  3,   6],
       [-12,   0]])

### Generowanie liczb pseudolosowych

###### Ustawienie ziarna losowania

In [0]:
np.random.seed(0)

In [66]:
np.random.randn()

1.764052345967664

In [67]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [68]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [69]:
np.random.rand()

0.1965823616800535

In [70]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [71]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [72]:
np.random.randint(10)

3

In [73]:
np.random.randint(low=10, high=101, size=10)

array([56, 52, 66, 70, 87, 40, 34, 12, 13, 23])

In [74]:
np.random.choice([4,2,1,4,6])

4

In [75]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [76]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.random.shuffle(data)

In [78]:
data

array([4, 1, 9, 6, 5, 2, 0, 7, 3, 8])

### Podstawowe funkcje

######### Stała eulera, Exponent, uzywana w sieciach neuronowych

In [79]:
np.exp(1)

2.718281828459045

######### Pierwiastek kwadratowy z konkretnej liczby w postaci float

In [80]:
np.sqrt(9)

3.0

######## Sprawdza czy wszystkie obiekty sa true

In [81]:
np.all([2,3,1])

True

######### Sprawdza czy jakikolwiek obiekt jest true

In [82]:
np.any([1,2,1])

True

In [83]:
np.any([0,0,0])

False

In [84]:
bool(0)

False

In [85]:
bool(2.5)

True

In [86]:
A = np.random.randn(5)
A

array([ 0.3869025 , -0.07055723,  0.60415971,  0.472149  ,  0.81991729])

######### Funkcja argmax zwraca najwiekszy argument w postaci NUMERU INDEKSU !!! wiadomka liczymy od 0

In [87]:
np.argmax(A)

4

########## Wyznaczenie wartosci tej wlasnie najwiekszej, wyciecie jej zeby pokazac ktora to (nie w postaci indeksu tylko wartosci)

In [88]:
A[np.argmax(A)]

0.8199172930519578

In [89]:
A

array([ 0.3869025 , -0.07055723,  0.60415971,  0.472149  ,  0.81991729])

In [90]:
np.argmin(A)

1

In [91]:
A[np.argmin(A)]

-0.07055722918362475

########## Sortowanie argumentow pokazujace wartosci posortowane PO INDEKSACH

In [92]:
np.argsort(A)

array([1, 0, 3, 2, 4])

In [93]:
np.max(A)

0.8199172930519578

In [94]:
np.min(A)

-0.07055722918362475

In [95]:
np.mean(A)

0.4425142532721112

In [96]:
np.median(A)

0.4721489975165859

In [97]:
np.std(A)

0.2952204392312453

### Indeksowanie i wycinanie tablic

In [98]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [100]:
A[2]

2

In [101]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [102]:
A[:2]

array([0, 1])

In [103]:
A[[0,2]]

array([0, 2])

In [104]:
A[-1]

19

In [105]:
A[10:15]

array([10, 11, 12, 13, 14])

In [106]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [107]:
A[0]

array([0, 1, 2, 3, 4])

######### Wyciecie kolumny

In [108]:
A[:, 0]

array([ 0,  5, 10, 15])

In [109]:
A[:, -1]

array([ 4,  9, 14, 19])

######### Wycięcie konkretnego elementu

In [110]:
A[1,1]

6

In [112]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

############## Przypisanie nowej wartości

In [113]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Iteracja po tablicach

In [114]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [115]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [116]:
for row in A:
  print(row[0])

0
5
10
15


In [117]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


##### Iteracja element po elemencie

In [118]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### Zmiana rozmiaru tablic

In [119]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [120]:
A.shape

(4, 5)

In [121]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

##### Zmiana do postaci jednowymiarowej

In [122]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

##### Transponowanie tablicy czyli zamiana wiersza na kolumne i odwrotnie

In [123]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### Maski logiczne

In [127]:
A = np.arange(start=-10, stop=10, step=0.5)
A=A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [128]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [129]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [130]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [131]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [132]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [133]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])